name: Noddit CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      SERVER_URL: http://127.0.0.1
      NODE_ENV: production
      MONGO_URL: mongodb://172.17.0.1:27017/noddit-test
      REDIS_URL: redis://172.17.0.1:6379
      PORT: 3000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: 90d
      JWT_COOKIE_EXPIRES_IN: 90
      EMAIL_FROM_NAME: ${{ secrets.EMAIL_FROM_NAME }}
      EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
      SENDGRID_USERNAME: ${{ secrets.SENDGRID_USERNAME }}
      SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.4.0

      - name: Build the Docker image
        run: docker build . --file Dockerfile --target test --tag arjanaswal/noddit:test

      - name: Run the Docker image for tests
        run: docker run -e SERVER_URL=$SERVER_URL -e NODE_ENV=$NODE_ENV -e MONGO_URL=$MONGO_URL -e REDIS_URL=$REDIS_URL -e PORT=$PORT -e JWT_SECRET=$JWT_SECRET -e JWT_EXPIRES_IN=$JWT_EXPIRES_IN -e JWT_COOKIE_EXPIRES_IN=$JWT_COOKIE_EXPIRES_IN -e EMAIL_FROM_NAME="$EMAIL_FROM_NAME" -e EMAIL_FROM_ADDRESS=$EMAIL_FROM_ADDRESS -e SENDGRID_USERNAME=$SENDGRID_USERNAME -e SENDGRID_PASSWORD=$SENDGRID_PASSWORD -e AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID -e AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY -e AWS_S3_BUCKET=$AWS_S3_BUCKET --rm -p 3000:3000 arjanaswal/noddit:test
